import { Rubik } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Navbar from "@/components/navbar/Navbar";
import AuthProvider from "@/context/AuthProvider";
const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <Suspense>
          <body className={rubik.className}>
        <AuthProvider>
            <Navbar />
            {children}
            {/* <div>FOOTER</div> */}
    </AuthProvider>
          </body>
        </Suspense>
      </html>
  );
}
