import { Rubik } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Navbar from "@/components/navbar/Navbar";
const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Suspense>
        <body className={rubik.className}>
          <Navbar />
          {children}
          {/* <div>FOOTER</div> */}
        </body>
      </Suspense>
    </html>
  );
}
